import { chromium, expect } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
const browser = await chromium.launch({ executablePath: '/home/norman/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome', headless: true, args: ['--no-sandbox'] });
const receipt = { defects: [], pageErrors: [], browserClosed: false };
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
  page.on('pageerror', error => receipt.pageErrors.push(error.message));
  await page.goto('http://127.0.0.1:4187');
  const click = name => page.getByRole('button', { name, exact: true }).click();
  await click('Settings');
  const backup = { schemaVersion: 1, gym: { availableEquipment: [] }, plans: [{ id: 'imported-plan', name: 'Imported routine', source: 'manual', createdAt: '2026-09-12T00:00:00Z', updatedAt: '2026-09-12T00:00:00Z', days: [{ id: 'imported-day', name: 'Imported session', items: [] }] }], activePlanId: null, aiPreferences: null };
  await page.getByLabel('Backup JSON').fill(JSON.stringify(backup));
  await click('Import backup');
  await expect(page.getByRole('alert')).toHaveCount(0);
  await click('Plan');
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('Imported routine');
  await expect(page.getByLabel('Your saved plans')).toHaveValue('imported-plan');
  await page.screenshot({ path: '.omo/evidence/ui-verification/edge-null-active-before.png' });
  await click('Add a movement');
  await page.getByRole('button', { name: /^Add .* to plan$/ }).first().click();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('gplan.state.v1')));
  expect(saved.plans).toHaveLength(2);
  expect(saved.plans.find(p => p.id === 'imported-plan').days[0].items).toHaveLength(0);
  await click('View plan');
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('My training plan');
  await page.screenshot({ path: '.omo/evidence/ui-verification/edge-null-active-after.png' });
  receipt.defects.push({ id: 'UI-V1', action: 'Import valid backup with one plan and activePlanId:null -> Plan shows Imported routine selected -> Add a movement -> first catalog Add -> View plan', expected: 'Add to the displayed selected Imported routine', actual: 'A second My training plan is created and activated; Imported routine stays empty', persisted: saved });
  await click('Settings');
  await page.getByLabel('Provider', { exact: true }).selectOption('openai-compatible');
  await page.getByLabel('Provider root URL').fill('http://provider.example/v1');
  await page.getByLabel('Manual model ID').fill('example-model');
  await click('Save AI preferences');
  const prefs = await page.evaluate(() => JSON.parse(localStorage.getItem('gplan.state.v1')).aiPreferences);
  expect(prefs.config.baseUrl).toBe('http://provider.example/v1');
  await expect(page.getByRole('alert')).toHaveCount(0);
  await page.getByLabel('Manual model ID').scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.omo/evidence/ui-verification/edge-http-saved.png' });
  const requests = [];
  page.on('request', request => { if (request.url().includes('provider.example')) requests.push(request.url()); });
  await click('Discover models');
  await expect(page.getByRole('alert')).toBeVisible();
  const error = await page.getByRole('alert').textContent();
  expect(requests).toHaveLength(0);
  await page.getByRole('alert').scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.omo/evidence/ui-verification/edge-http-rejected.png' });
  receipt.defects.push({ id: 'UI-V2', action: 'Set OpenAI-compatible root URL http://provider.example/v1 and manual model example-model -> Save AI preferences -> Discover models', expected: 'Reject unsupported provider root before reporting saved preferences', actual: 'Preferences save successfully, but the real adapter immediately rejects discovery without HTTP', savedPreferences: prefs, error, requests });
  expect(receipt.pageErrors).toEqual([]);
} finally {
  await browser.close();
  receipt.browserClosed = true;
  await writeFile('.omo/evidence/ui-verification/edge-receipts.json', JSON.stringify(receipt, null, 2));
}
console.log(JSON.stringify(receipt, null, 2));
