import { animation, defineExercises } from './build';

export const lowerExercises = [
  ...defineExercises({ primary:['adductors'], secondary:[], movement:'hip-isolation', prescription:'reps', animation:animation('static','seated','machine'), cues:['Bring the working leg or legs toward your midline while keeping your pelvis steady.', 'Return slowly through a comfortable range without bouncing or forcing a stretch.'] }, [
    ['Seated hip adduction', [['hip-adductor']], 'Set the machine pads against your inner thighs and choose a comfortable starting width; sit with your back supported.'],
    ['Cable hip adduction', [['cable']], 'Stand side-on to a low pulley with the cuff around the nearer ankle; draw that leg inward across your body, then repeat on the other side.', { animation:{ ...animation('static','standing','cable'), unilateral:true } }],
  ]),
  ...defineExercises({ primary:['quads','glutes'], secondary:['core'], movement:'squat', prescription:'reps', animation:animation('squat','standing'), cues:['Sit down between your hips with knees tracking over your toes and heels grounded.', 'Drive through your whole foot to stand; keep your trunk braced and use a controlled depth.'] }, [
    ['Bodyweight squat', [[]], 'Stand with feet around shoulder width and toes turned slightly outward.'],
    ['Goblet squat', [['dumbbells'],['kettlebell']], 'Hold one dumbbell or kettlebell close to your chest with elbows pointing down.', { animation:animation('squat','standing','dumbbells') }],
    ['Barbell back squat', [['barbell','rack']], 'Set rack safeties below your squat depth and place the bar across your upper traps.', { animation:animation('squat','standing','barbell'), difficulty:'intermediate' }],
    ['Barbell front squat', [['barbell','rack']], 'Unrack onto the front of your shoulders with elbows high; use safety arms.', { animation:animation('squat','standing','barbell'), difficulty:'advanced' }],
    ['Dumbbell squat', [['dumbbells']], 'Hold dumbbells at your sides with arms straight.', { animation:animation('squat','standing','dumbbells') }],
    ['Smith machine squat', [['smith-machine']], 'Set safety stops and place the bar on your upper traps with feet slightly forward.', { animation:animation('squat','standing','machine') }],
    ['Box squat', [['bench']], 'Stand just in front of a stable bench; touch down lightly without rocking backward.'],
    ['Sumo dumbbell squat', [['dumbbells'],['kettlebell']], 'Take a comfortably wide stance with toes turned out and hold the weight between your legs.', { animation:animation('squat','standing','dumbbells') }],
    ['Paused bodyweight squat', [[]], 'Use your normal squat stance and hold the bottom position briefly before standing.'],
    ['Leg press', [['leg-press']], 'Set your feet shoulder-width on the sled, secure your back against the pad, and release the safety handles.', { animation:animation('squat','seated','machine'), secondary:[] }],
    ['Single-leg leg press', [['leg-press']], 'Use a light load and place one foot centrally on the sled; perform equal repetitions on each side.', { animation:{ ...animation('squat','seated','machine'), unilateral:true }, secondary:[], difficulty:'intermediate' }],
  ]),
  ...defineExercises({ primary:['hamstrings','glutes'], secondary:['back','core'], movement:'hinge', prescription:'reps', animation:animation('hinge','standing','dumbbells'), cues:['Push your hips backward with soft knees, keeping the load close and your spine neutral.', 'Stop when your hamstrings limit the range, then drive your hips forward without leaning back.'] }, [
    ['Barbell Romanian deadlift', [['barbell']], 'Lift the bar to standing, hold it against your thighs, and keep a small knee bend.', { aliases:['RDL','Romanian deadlift'], animation:animation('hinge','standing','barbell'), difficulty:'intermediate' }],
    ['Dumbbell Romanian deadlift', [['dumbbells']], 'Stand holding two dumbbells against the front of your thighs.', { aliases:['dumbbell RDL'] }],
    ['Kettlebell Romanian deadlift', [['kettlebell']], 'Hold a kettlebell by its handle in front of your thighs.'],
    ['Single-leg Romanian deadlift', [['dumbbells'],['kettlebell']], 'Balance on one leg while the other reaches backward; hold a light weight and repeat both sides.', { animation:{ ...animation('hinge','standing','dumbbells'), unilateral:true }, difficulty:'intermediate' }],
    ['Bodyweight good morning', [[]], 'Stand with hands across your chest and knees softly bent.', { animation:animation('hinge','standing') }],
    ['Barbell good morning', [['barbell','rack']], 'Unrack a light bar onto your upper traps with safety arms set appropriately.', { animation:animation('hinge','standing','barbell'), difficulty:'advanced' }],
    ['Cable pull-through', [['cable']], 'Face away from a low pulley and hold a rope between your legs; step forward to tension the cable.', { animation:animation('hinge','standing','cable') }],
    ['Band good morning', [['bands']], 'Stand on a loop band and place the other end across your upper back, not your neck.', { animation:animation('hinge','standing') }],
  ]),
  ...defineExercises({ primary:['glutes','quads'], secondary:['hamstrings','back','core'], movement:'hinge', prescription:'reps', animation:animation('hinge','standing','barbell'), cues:['Brace, push the floor away, and lift while keeping the weight close to your body.', 'Stand tall without leaning back; hinge and bend your knees to return the weight under control.'] }, [
    ['Barbell deadlift', [['barbell']], 'Set the bar over midfoot, grip just outside your legs, and take the slack out with a neutral spine.', { difficulty:'intermediate' }],
    ['Sumo deadlift', [['barbell']], 'Use a wide stance with toes out and grip the bar between your knees.', { difficulty:'intermediate' }],
    ['Kettlebell deadlift', [['kettlebell']], 'Place a kettlebell between your feet and reach down by bending your hips and knees.', { animation:animation('hinge','standing','dumbbells') }],
  ]),
  ...defineExercises({ primary:['quads','glutes'], secondary:['hamstrings','core'], movement:'lunge', prescription:'reps', animation:{ ...animation('lunge','standing'), unilateral:true }, cues:['Lower your back knee toward the floor while keeping your front foot planted and knee aligned.', 'Push through the front leg to rise with control; complete equal repetitions on both sides.'] }, [
    ['Reverse lunge', [[]], 'Stand tall and take a controlled step backward before lowering.'],
    ['Forward lunge', [[]], 'Step forward far enough to keep your front heel grounded as you lower.'],
    ['Split squat', [[]], 'Begin in a staggered stance and keep both feet in place throughout the set.'],
    ['Dumbbell reverse lunge', [['dumbbells']], 'Hold dumbbells at your sides and step backward one leg at a time.', { animation:{ ...animation('lunge','standing','dumbbells'), unilateral:true } }],
    ['Dumbbell split squat', [['dumbbells']], 'Hold dumbbells at your sides with feet in a stable staggered stance.', { animation:{ ...animation('lunge','standing','dumbbells'), unilateral:true } }],
    ['Bulgarian split squat', [['bench']], 'Place the top of your back foot on a low stable bench and position the front foot well forward.', { difficulty:'intermediate' }],
    ['Dumbbell Bulgarian split squat', [['dumbbells','bench']], 'Rest your back foot on a bench and hold dumbbells at your sides.', { animation:{ ...animation('lunge','standing','dumbbells'), unilateral:true }, difficulty:'intermediate' }],
    ['Walking lunge', [[]], 'Choose a clear level path and step forward into each lunge, bringing the rear leg through.', { difficulty:'intermediate' }],
  ]),
  ...defineExercises({ primary:['quads'], secondary:[], movement:'knee-extension', prescription:'reps', animation:animation('extension','seated','machine'), cues:['Straighten the knee smoothly without kicking or lifting your hips.', 'Lower slowly into a comfortable bend and keep the thigh supported.'] }, [
    ['Leg extension', [['leg-extension']], 'Align your knees with the machine pivot and position the shin pad just above your ankles.'],
    ['Single-leg extension', [['leg-extension']], 'Set the pivot at your knee and use one leg at a time with a lighter load.', { animation:{ ...animation('extension','seated','machine'), unilateral:true } }],
    ['Seated band knee extension', [['bands','bench']], 'Sit on a bench and anchor a band behind your ankle to a secure low point; extend one knee and repeat both sides.', { animation:{ ...animation('extension','seated'), unilateral:true } }],
  ]),
  ...defineExercises({ primary:['hamstrings'], secondary:[], movement:'knee-flexion', prescription:'reps', animation:animation('leg-curl','prone','machine'), cues:['Bend your knees to bring your heels toward your hips without arching your lower back.', 'Straighten the knees slowly, retaining tension rather than letting the load drop.'] }, [
    ['Lying leg curl', [['leg-curl']], 'Use a prone leg-curl machine with knees aligned to the pivot and the roller above your heels.'],
    ['Seated leg curl', [['leg-curl']], 'Use a seated leg-curl machine; secure the thigh pad and align your knees to its pivot.', { animation:animation('leg-curl','seated','machine') }],
    ['Single-leg lying curl', [['leg-curl']], 'Set up on a prone leg-curl machine and work one leg at a time with a lighter load.', { animation:{ ...animation('leg-curl','prone','machine'), unilateral:true } }],
    ['Stability-ball leg curl', [['stability-ball']], 'Lie on your back with heels on the ball; raise your hips and roll the ball toward you.', { secondary:['glutes','core'], animation:animation('leg-curl','supine'), difficulty:'intermediate' }],
    ['Prone band leg curl', [['bands']], 'Anchor a band low beyond your feet and loop it around an ankle while lying face down; repeat both legs.', { animation:{ ...animation('leg-curl','prone'), unilateral:true } }],
  ]),
  ...defineExercises({ primary:['glutes'], secondary:['hamstrings'], movement:'hip-isolation', prescription:'reps', animation:animation('hinge','supine'), cues:['Press through your feet and raise your hips while keeping ribs down.', 'Squeeze the glutes at the top without arching your back, then lower slowly.'] }, [
    ['Glute bridge', [[]], 'Lie on your back with knees bent, feet hip-width apart, and arms by your sides.'],
    ['Single-leg glute bridge', [[]], 'Start in a bridge setup and lift one knee toward your chest; repeat both sides.', { animation:{ ...animation('hinge','supine'), unilateral:true }, difficulty:'intermediate' }],
    ['Barbell hip thrust', [['barbell','bench']], 'Rest your upper back on a stable bench and position a padded bar across your hip crease.', { animation:animation('hinge','supine','barbell'), difficulty:'intermediate' }],
    ['Dumbbell glute bridge', [['dumbbells']], 'Lie on your back and hold a padded dumbbell securely across your hip crease.', { animation:animation('hinge','supine','dumbbells') }],
  ]),
  ...defineExercises({ primary:['glutes'], secondary:[], movement:'hip-isolation', prescription:'reps', animation:animation('raise','standing'), cues:['Move the leg away from your midline without rotating your pelvis or leaning.', 'Return slowly to the starting position and repeat evenly on both sides.'] }, [
    ['Standing band hip abduction', [['bands']], 'Loop a band around your ankles and use a wall for balance.'],
    ['Cable hip abduction', [['cable']], 'Attach a low cable to your outside ankle and stand side-on to the pulley.', { animation:{ ...animation('raise','standing','cable'), unilateral:true } }],
    ['Seated hip abduction', [['hip-abductor']], 'Adjust an abduction machine so pads rest outside your knees and keep your back on the pad.', { animation:animation('raise','seated','machine') }],
    ['Side-lying hip abduction', [[]], 'Lie on your side with legs long; lift the top leg without rolling your hips backward.', { animation:{ ...animation('raise','supine'), unilateral:true } }],
  ]),
  ...defineExercises({ primary:['calves'], secondary:[], movement:'plantar-flexion', prescription:'reps', animation:animation('calf-raise','standing'), cues:['Rise onto the balls of your feet while keeping ankles aligned, pausing at the top.', 'Lower your heels slowly through a comfortable range without bouncing.'] }, [
    ['Standing calf raise', [[]], 'Stand with feet hip-width apart and use a wall lightly for balance.'],
    ['Single-leg calf raise', [[]], 'Stand on one foot and use a wall for balance; complete both sides.', { animation:{ ...animation('calf-raise','standing'), unilateral:true } }],
    ['Dumbbell calf raise', [['dumbbells']], 'Hold dumbbells at your sides and stand on a flat floor.', { animation:animation('calf-raise','standing','dumbbells') }],
    ['Machine calf raise', [['calf-machine']], 'Fit the shoulder or thigh pads to the machine design and place the balls of your feet on its platform.', { animation:animation('calf-raise','standing','machine') }],
    ['Seated dumbbell calf raise', [['dumbbells','bench']], 'Sit on a bench with knees bent and padded dumbbells resting securely above your knees.', { animation:animation('calf-raise','seated','dumbbells') }],
    ['Leg press calf raise', [['leg-press']], 'Keep the sled safety system engaged as designed, legs nearly straight, and balls of feet securely on the lower platform.', { animation:animation('calf-raise','seated','machine') }],
    ['Smith machine calf raise', [['smith-machine']], 'Set safety stops, rest the bar across your upper traps, and stand with feet under your hips.', { animation:animation('calf-raise','standing','machine') }],
  ]),
];
