import { animation, defineExercises } from './build';

export const upperExercises = [
  ...defineExercises({ primary:['chest'], secondary:['shoulders','triceps'], movement:'horizontal-push', prescription:'reps', animation:animation('horizontal-press','supine','dumbbells'), cues:['Lower with forearms vertical and elbows about 45 degrees from your torso.', 'Press upward without bouncing or lifting your shoulders off the support.'] }, [
    ['Barbell bench press', [['barbell','bench','rack']], 'Lie on a flat bench with feet planted; unrack the bar over your chest with a spotter or safety arms.', { animation:animation('horizontal-press','supine','barbell') }],
    ['Dumbbell bench press', [['dumbbells','bench']], 'Lie on a flat bench with one dumbbell above each shoulder.'],
    ['Incline dumbbell press', [['dumbbells','bench']], 'Set an adjustable bench to a low incline and hold the dumbbells over your upper chest.'],
    ['Incline barbell press', [['barbell','bench','rack']], 'Use a low incline bench inside a rack with safeties; unrack above your upper chest.', { animation:animation('horizontal-press','supine','barbell') }],
    ['Dumbbell floor press', [['dumbbells']], 'Lie on the floor with knees bent; pause when your upper arms gently touch the floor.'],
    ['Barbell floor press', [['barbell','rack']], 'Set a rack over floor space and safeties at arm level; unrack while lying on the floor.', { animation:animation('horizontal-press','supine','barbell'), difficulty:'intermediate' }],
    ['Neutral-grip dumbbell press', [['dumbbells','bench']], 'Lie on a bench holding the dumbbells with palms facing each other.'],
    ['Dumbbell squeeze press', [['dumbbells','bench']], 'Lie on a bench and keep the inner ends of the dumbbells gently pressed together throughout the lift.'],
    ['Smith machine bench press', [['smith-machine','bench']], 'Place a flat bench under the Smith bar and set the stops above chest height.', { animation:animation('horizontal-press','supine','machine') }],
    ['Machine chest press', [['chest-press']], 'Adjust the seat so the handles are at mid-chest level and keep your back against the pad.', { animation:animation('horizontal-press','seated','machine') }],
  ]),
  ...defineExercises({ primary:['chest'], secondary:['shoulders','triceps','core'], movement:'horizontal-push', prescription:'reps', animation:animation('horizontal-press','prone'), cues:['Bend your elbows and lower your chest while keeping ribs and pelvis aligned.', 'Push the surface away and return with a straight body; avoid flaring elbows.'] }, [
    ['Push-up', [[]], 'Place hands slightly wider than shoulders on the floor and extend your legs behind you.', { aliases:['press up','pushup'] }],
    ['Knee push-up', [[]], 'Support yourself on hands and knees; make a straight line from shoulders to knees.'],
    ['Wall push-up', [[]], 'Place hands on a wall at shoulder height and step back to a manageable angle.'],
    ['Incline push-up', [['bench']], 'Grip the edges of a stable bench and step back into a straight plank.'],
    ['Decline push-up', [['bench']], 'Place your feet on a stable bench and hands on the floor.', { difficulty:'intermediate' }],
    ['Wide push-up', [[]], 'Set your hands moderately wider than shoulder width; use a pain-free shoulder range.', { difficulty:'intermediate' }],
    ['Paused push-up', [[]], 'Take a normal push-up position and pause briefly just above the floor each repetition.', { difficulty:'intermediate' }],
  ]),
  ...defineExercises({ primary:['chest'], secondary:['shoulders'], movement:'horizontal-push', prescription:'reps', animation:animation('horizontal-press','standing','cable'), cues:['Bring your arms together in an arc with a small, fixed elbow bend.', 'Return slowly until you feel a comfortable chest stretch, without forcing the shoulder backward.'] }, [
    ['Cable chest fly', [['cable']], 'Set dual pulleys at chest height; stand in a split stance with a handle in each hand.'],
    ['Low-to-high cable fly', [['cable']], 'Set dual pulleys low and sweep the handles toward upper-chest height.'],
    ['High-to-low cable fly', [['cable']], 'Set dual pulleys high and bring the handles together in front of your lower chest.'],
    ['Pec deck fly', [['pec-deck']], 'Adjust the seat to align the handles with your chest and keep your back supported.', { animation:animation('horizontal-press','seated','machine') }],
    ['Dumbbell fly', [['dumbbells','bench']], 'Lie on a flat bench with dumbbells above your chest; use a light load.', { animation:animation('horizontal-press','supine','dumbbells') }],
    ['Band chest fly', [['bands']], 'Secure a band at chest height behind you and hold one end in each hand.', { animation:animation('horizontal-press','standing') }],
  ]),
  ...defineExercises({ primary:['shoulders'], secondary:['triceps'], movement:'vertical-push', prescription:'reps', animation:animation('vertical-press','standing','dumbbells'), cues:['Brace your abdomen and press overhead without leaning backward.', 'Lower under control to shoulder height with wrists stacked over elbows.'] }, [
    ['Standing dumbbell overhead press', [['dumbbells']], 'Stand with feet hip-width and dumbbells at shoulder level.'],
    ['Seated dumbbell shoulder press', [['dumbbells','bench']], 'Sit against an upright bench with feet planted.', { animation:animation('vertical-press','seated','dumbbells') }],
    ['Barbell overhead press', [['barbell','rack']], 'Unrack at upper-chest height and grip just outside shoulder width.', { animation:animation('vertical-press','standing','barbell'), difficulty:'intermediate' }],
    ['Machine shoulder press', [['shoulder-press']], 'Set the seat so the handles start near shoulder height; keep your back on the pad.', { animation:animation('vertical-press','seated','machine') }],
    ['Arnold press', [['dumbbells','bench']], 'Sit upright with palms facing you, then rotate the palms forward as you press.', { animation:animation('vertical-press','seated','dumbbells'), difficulty:'intermediate' }],
    ['Single-arm kettlebell press', [['kettlebell']], 'Hold a kettlebell in the rack position with a straight wrist; complete both sides.', { animation:{ ...animation('vertical-press','standing','dumbbells'), unilateral:true }, secondary:['triceps','core'], difficulty:'intermediate' }],
    ['Band overhead press', [['bands']], 'Stand on the center of a band and hold the ends at your shoulders.', { animation:animation('vertical-press','standing') }],
    ['Pike push-up', [[]], 'Place hands on the floor, raise hips, and lower the crown of your head between your hands.', { animation:animation('vertical-press','prone'), difficulty:'intermediate' }],
  ]),
  ...defineExercises({ primary:['back'], secondary:['biceps','shoulders'], movement:'horizontal-pull', prescription:'reps', animation:animation('horizontal-pull','standing','dumbbells'), cues:['Pull your elbows toward your hips without shrugging or jerking your torso.', 'Extend your arms slowly, allowing the shoulder blades to move while keeping your trunk steady.'] }, [
    ['Bent-over dumbbell row', [['dumbbells']], 'Hinge at your hips, bend your knees slightly, and let both dumbbells hang.'],
    ['Single-arm dumbbell row', [['dumbbells','bench']], 'Support one hand and knee on a bench; row with the other arm and repeat both sides.', { animation:{ ...animation('horizontal-pull','quadruped','dumbbells'), unilateral:true } }],
    ['Barbell bent-over row', [['barbell']], 'Hinge with a flat back and hold the bar just below knee level.', { animation:animation('horizontal-pull','standing','barbell'), difficulty:'intermediate' }],
    ['Underhand barbell row', [['barbell']], 'Hinge and grip the bar with palms forward, keeping elbows close to your sides.', { animation:animation('horizontal-pull','standing','barbell'), difficulty:'intermediate' }],
    ['Chest-supported dumbbell row', [['dumbbells','bench']], 'Lie chest-down on an incline bench and let your arms hang beside it.', { animation:animation('horizontal-pull','prone','dumbbells') }],
    ['Seated cable row', [['cable']], 'Sit at a low-row cable station with knees softly bent and torso upright.', { animation:animation('horizontal-pull','seated','cable') }],
    ['Machine seated row', [['seated-row']], 'Adjust the chest support so you can reach the handles without rounding your back.', { animation:animation('horizontal-pull','seated','machine') }],
    ['Standing band row', [['bands']], 'Anchor the band securely at lower-chest height and step back to take up slack.', { animation:animation('horizontal-pull','standing') }],
    ['Inverted row', [['barbell','rack'],['smith-machine']], 'Secure the bar around waist height and hang underneath with heels on the floor.', { animation:animation('horizontal-pull','supine','barbell'), difficulty:'intermediate' }],
    ['Single-arm cable row', [['cable']], 'Stand facing a chest-height pulley, brace in a split stance, and row one handle; repeat both sides.', { animation:{ ...animation('horizontal-pull','standing','cable'), unilateral:true } }],
    ['Kettlebell row', [['kettlebell']], 'Hinge with one hand braced on your thigh; row the kettlebell on the opposite side, then switch.', { animation:{ ...animation('horizontal-pull','standing','dumbbells'), unilateral:true } }],
  ]),
  ...defineExercises({ primary:['back'], secondary:['biceps'], movement:'vertical-pull', prescription:'reps', animation:animation('vertical-pull','seated','machine'), cues:['Draw your elbows down toward your ribs without swinging or pulling behind your neck.', 'Return slowly to an overhead reach while maintaining control of your shoulders.'] }, [
    ['Lat pulldown', [['lat-pulldown']], 'Set the thigh pad snugly and grip the bar just wider than shoulders.'],
    ['Neutral-grip lat pulldown', [['lat-pulldown']], 'Attach parallel handles and sit with thighs secured under the pad.'],
    ['Underhand lat pulldown', [['lat-pulldown']], 'Use a shoulder-width palms-toward-you grip and keep your chest tall.'],
    ['Pull-up', [['pullup-bar']], 'Hang from a secure bar with palms facing away and shoulders engaged.', { animation:animation('vertical-pull','standing'), difficulty:'advanced' }],
    ['Chin-up', [['pullup-bar']], 'Hang from a secure bar with palms toward you and hands shoulder-width apart.', { animation:animation('vertical-pull','standing'), difficulty:'intermediate' }],
    ['Assisted pull-up', [['assisted-pullup']], 'Select enough assistance for control and place knees or feet on the support pad.', { animation:animation('vertical-pull','standing','machine') }],
    ['Band-assisted pull-up', [['pullup-bar','bands']], 'Loop an intact band over a secure bar and place a foot or knee in the loop carefully.', { animation:animation('vertical-pull','standing'), difficulty:'intermediate' }],
    ['Kneeling band pulldown', [['bands']], 'Anchor a band overhead and kneel beneath it with the ends in your hands.', { animation:animation('vertical-pull','seated') }],
    ['Single-arm cable pulldown', [['cable']], 'Kneel facing a high pulley, hold one handle overhead, and repeat on both sides.', { animation:{ ...animation('vertical-pull','seated','cable'), unilateral:true } }],
    ['Straight-arm cable pulldown', [['cable']], 'Face a high pulley, hinge slightly, and hold the bar with nearly straight elbows; sweep it to your thighs.', { secondary:['triceps'], animation:animation('vertical-pull','standing','cable') }],
  ]),
  ...defineExercises({ primary:['shoulders'], secondary:[], movement:'shoulder-isolation', prescription:'reps', animation:animation('raise','standing','dumbbells'), cues:['Raise with a soft elbow and quiet torso; stop around shoulder height.', 'Lower slowly without shrugging, swinging, or forcing a painful range.'] }, [
    ['Dumbbell lateral raise', [['dumbbells']], 'Stand holding dumbbells at your sides; lift outward slightly forward of your torso.'],
    ['Seated lateral raise', [['dumbbells','bench']], 'Sit on a bench with feet flat and lift the dumbbells out to your sides.', { animation:animation('raise','seated','dumbbells') }],
    ['Cable lateral raise', [['cable']], 'Stand side-on to a low pulley and lift the outside arm across and away from your body; repeat both sides.', { animation:{ ...animation('raise','standing','cable'), unilateral:true } }],
    ['Band lateral raise', [['bands']], 'Stand on the middle of a band and lift the ends sideways.', { animation:animation('raise','standing') }],
    ['Dumbbell front raise', [['dumbbells']], 'Hold dumbbells in front of your thighs and lift forward.'],
    ['Bent-over reverse fly', [['dumbbells']], 'Hinge at the hips and lift dumbbells out to the sides with your chest facing the floor.', { secondary:['back'], animation:animation('raise','prone','dumbbells') }],
    ['Reverse pec deck', [['pec-deck']], 'Set a reverse-fly-capable pec deck for rear delts and sit facing the pad; open the arms outward.', { secondary:['back'], animation:animation('raise','seated','machine') }],
    ['Cable face pull', [['cable']], 'Set a rope at eye height and pull toward your forehead with elbows wide, finishing with hands beside your ears.', { secondary:['back'], animation:animation('horizontal-pull','standing','cable') }],
    ['Band pull-apart', [['bands']], 'Hold a band at chest height with arms forward and pull the hands apart until the band approaches your chest.', { secondary:['back'], animation:animation('raise','standing') }],
  ]),
];
