import { test, expect, savedState, emptyBackup, activeServiceWorker, goOffline, reloadOffline } from './support.js';

// Known catalog choices, independent of the app's ranking implementation.
const swapName = 'Dumbbell floor press';

test('mobile plan edit swap and persistence', async ({ page, qa }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await qa.action('open production app', () => page.goto('/'));
  await qa.click('Chest');
  await qa.select('Filter equipment', 'dumbbells');
  await qa.action('enable My gym only', () => page.getByLabel('My gym only').check());
  await expect(page.getByRole('button', { name: 'Chest', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('button', { name: 'View Barbell bench press', exact: true })).toHaveCount(0);
  await qa.draw('open Dumbbell bench press', () => qa.click('View Dumbbell bench press'));
  await qa.overflow();
  await qa.shot('mobile-real-3d');
  await qa.click('Add to plan');
  await qa.click('View plan');
  const original = await savedState(page);
  await qa.fill('Plan name', 'Release strength');
  await qa.fill('Sets', '4');
  await qa.click('Swap exercise');
  const candidate = page.locator('.swap-option').filter({ has: page.locator('strong', { hasText: new RegExp(`^${swapName}$`) }) });
  await expect(candidate).toHaveCount(1);
  await qa.action(`choose compatible ${swapName}`, () => candidate.click());
  const edited = await savedState(page);
  expect(edited.plans).toHaveLength(1);
  expect(edited.plans[0].id).toBe(original.plans[0].id);
  expect(edited.plans[0].days[0].items[0]).toMatchObject({ id: original.plans[0].days[0].items[0].id, exerciseId: 'dumbbell-floor-press', sets: 4 });
  await qa.action('reload saved mobile plan', () => page.reload());
  await qa.click('Plan');
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('Release strength');
  await expect(page.getByLabel('Sets', { exact: true })).toHaveValue('4');
  await expect(page.getByRole('button', { name: swapName, exact: true })).toBeVisible();
  expect(await savedState(page)).toEqual(edited);
  await qa.overflow();
  await page.locator('.plan-item').scrollIntoViewIfNeeded();
  await qa.shot('mobile-saved-plan');
});

test('offline cold lazy graphics and imported null active plan', async ({ page, context, qa }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await qa.action('open fresh app without any online exercise detail', () => page.goto('/'));
  await qa.click('Settings');
  await qa.fill('Backup JSON', JSON.stringify(emptyBackup));
  await qa.click('Import backup');
  await qa.click('Plan');
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue(emptyBackup.plans[0].name);
  await expect(page.locator('.plan-item')).toHaveCount(0);
  await qa.click('Add a movement');
  await qa.click('Add Dumbbell bench press to plan');
  await qa.click('View plan');
  let state = await savedState(page);
  expect(state.plans).toHaveLength(1);
  expect(state.activePlanId).toBe('imported-plan');
  expect(state.plans[0].days[0]).toMatchObject({ id: 'imported-day', items: [{ exerciseId: 'dumbbell-bench-press' }] });
  // Preferences without a key let the offline dialog expose its disabled generation control.
  await qa.click('Settings');
  await qa.fill('Manual model ID', 'offline-fixture');
  await qa.click('Save AI preferences');
  const worker = await qa.action('await activated controller online', () => activeServiceWorker(page));
  qa.receipt.serviceWorker = worker;
  const onlineResources = await page.evaluate(() => performance.getEntriesByType('resource').map(entry => entry.name));
  expect(onlineResources.some(url => /ExerciseViewer-.*\.js/.test(url))).toBe(false);
  expect(await page.locator('canvas').count()).toBe(0);
  qa.receipt.onlineLazyGraphicsRequested = false;
  await qa.action('set isolated context offline and await offline event', () => goOffline(page, context));
  await qa.action('reload shell offline; native browser offline state; uncached network blocked', () => reloadOffline(page, context));
  expect(await page.evaluate(() => navigator.onLine)).toBe(false);
  await expect(page.getByTestId('exercise-card')).toHaveCount(158);
  await qa.click('Plan');
  await expect(page.getByLabel('Your saved plans')).toHaveValue('imported-plan');
  await expect(page.getByRole('button', { name: 'Dumbbell bench press', exact: true })).toBeVisible();
  await qa.click('Exercises');
  const graphicsResponse = page.waitForResponse(response => /ExerciseViewer-.*\.js/.test(response.url()));
  await qa.draw('first ever detail and lazy graphics import offline: Bodyweight squat', () => qa.click('View Bodyweight squat'));
  const response = await graphicsResponse;
  expect(response.fromServiceWorker()).toBe(true);
  expect(response.status()).toBe(200);
  qa.receipt.offlineGraphics = { url: response.url(), fromServiceWorker: response.fromServiceWorker(), status: response.status() };
  await qa.overflow();
  await qa.shot('offline-cold-real-3d');
  await qa.click('Add to plan');
  await qa.click('View plan');
  await qa.fill('Plan name', 'Saved without a network');
  await qa.action('edit first item to 4 sets offline', () => page.getByLabel('Sets', { exact: true }).first().fill('4'));
  state = await savedState(page);
  expect(state.plans).toHaveLength(1);
  expect(state.plans[0].days[0].items).toHaveLength(2);
  await qa.action('reload edited plan offline; native browser offline state; uncached network blocked', () => reloadOffline(page, context));
  await qa.click('Plan');
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('Saved without a network');
  await expect(page.getByLabel('Sets', { exact: true }).first()).toHaveValue('4');
  expect(await savedState(page)).toEqual(state);
  await qa.click('Plan with AI');
  await expect(page.getByRole('button', { name: 'Generate preview', exact: true })).toBeDisabled();
  await qa.overflow();
  await qa.shot('offline-ai-disabled');
  await qa.click('Close dialog');
  for (const surface of ['Exercises', 'Plan', 'Settings']) { await qa.click(surface); await qa.overflow(); }
  await expect(page.getByRole('button', { name: 'Discover models', exact: true })).toBeDisabled();
});

test('desktop surfaces and same canvas responsive camera', async ({ page, qa }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await qa.action('open desktop production app', () => page.goto('/'));
  await expect(page.getByLabel('Search exercises')).toBeVisible();
  await qa.shot('desktop-exercises');
  await qa.click('Plan');
  await expect(page.getByRole('button', { name: 'New plan', exact: true })).toBeVisible();
  await qa.overflow();
  await qa.click('Settings');
  await expect(page.getByLabel('Provider', { exact: true })).toBeVisible();
  await qa.overflow();
  await qa.click('Exercises');
  await qa.draw('open desktop Dumbbell curl', () => qa.click('View Dumbbell curl'));
  await qa.shot('desktop-real-3d');
  const canvas = await page.locator('.exercise-viewer canvas').elementHandle();
  expect(canvas).not.toBeNull();
  const resized = await qa.draw('resize mounted desktop canvas to 375', () => page.setViewportSize({ width: 375, height: 900 }));
  expect(await canvas.evaluate(element => element === document.querySelector('.exercise-viewer canvas'))).toBe(true);
  await qa.overflow();
  await qa.shot('retained-canvas-375');
  const side = await qa.draw('use side camera on retained canvas', () => qa.click('side view'));
  expect(side.fingerprint).not.toBe(resized.fingerprint);
  expect(await canvas.evaluate(element => element === document.querySelector('.exercise-viewer canvas'))).toBe(true);
  await qa.shot('retained-canvas-side');
});
